version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo:27017/openStreetMap
    networks:
      - qol-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    networks:
      - qol-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - qol-network

volumes:
  mongo-data:

networks:
  qol-network:
    driver: bridge
